# Copyright Rob Gage 2025

[package]
name = "web-interface"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]



[dependencies]
console_error_panic_hook = "0.1.7"
leptos = "0.8.14"
wasm-bindgen = "0.2.105"
