# Copyright Rob Gage 2025

[package]
name = "interface"
version = "0.0.0"
edition = "2024"

[dependencies]
engine = { version = "0.0.0", path = "../engine" }
syntax = { version = "0.0.0", path = "../syntax" }
